-- MySQL Script generated by MySQL Workbench
-- Mon Apr  5 20:47:21 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mobilityJobBD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mobilityJobBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mobilityJobBD` DEFAULT CHARACTER SET utf8 ;
USE `mobilityJobBD` ;

-- -----------------------------------------------------
-- Table `mobilityJobBD`.`MB_Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mobilityJobBD`.`MB_Users` (
  `idMB_User` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nameUser` VARCHAR(45) NOT NULL,
  `appUser` VARCHAR(45) NOT NULL,
  `apmUser` VARCHAR(45) NOT NULL,
  `naciUser` VARCHAR(45) NOT NULL,
  `genderUser` ENUM('H', 'M', 'O') NOT NULL,
  `CURPUser` VARCHAR(18) NOT NULL,
  `INEUser` VARCHAR(18) NOT NULL,
  `birthUser` DATE NOT NULL,
  `phoneUser` INT(10) NOT NULL,
  `mailUser` VARCHAR(45) NOT NULL,
  `passUser` VARCHAR(45) NOT NULL,
  `munAddressUser` VARCHAR(45) NOT NULL,
  `colAddressUser` VARCHAR(45) NOT NULL,
  `streetAddressUser` VARCHAR(45) NOT NULL,
  `officeUser` VARCHAR(45) NOT NULL,
  `cpAddressUser` INT(10) NOT NULL,
  `typeUser` ENUM('COL', 'CLI') NOT NULL,
  PRIMARY KEY (`idMB_User`),
  UNIQUE INDEX `idColaborator_UNIQUE` (`idMB_User` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobilityJobBD`.`MB_Services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mobilityJobBD`.`MB_Services` (
  `idMB_Services` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nameService` VARCHAR(45) NOT NULL,
  `typeService` VARCHAR(45) NOT NULL,
  `statusService` VARCHAR(10) NOT NULL,
  `priceService` VARCHAR(45) NOT NULL,
  `descriptionService` VARCHAR(45) NOT NULL,
  `MB_Users_idMB_User` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idMB_Services`),
  UNIQUE INDEX `idMB_Services_UNIQUE` (`idMB_Services` ASC) VISIBLE,
  INDEX `fk_MB_Services_MB_Users1_idx` (`MB_Users_idMB_User` ASC) VISIBLE,
  CONSTRAINT `fk_MB_Services_MB_Users1`
    FOREIGN KEY (`MB_Users_idMB_User`)
    REFERENCES `mobilityJobBD`.`MB_Users` (`idMB_User`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobilityJobBD`.`MB_Pays`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mobilityJobBD`.`MB_Pays` (
  `idMB_Pays` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `typePay` VARCHAR(45) NOT NULL,
  `cardNumber` INT(16) NOT NULL,
  `cardBinNumber` INT(3) NOT NULL,
  `entityPay` VARCHAR(45) NOT NULL,
  `MB_Users_idUser` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idMB_Pays`),
  UNIQUE INDEX `idMB_Pays_UNIQUE` (`idMB_Pays` ASC) VISIBLE,
  INDEX `fk_MB_Pays_MB_Users1_idx` (`MB_Users_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_MB_Pays_MB_Users1`
    FOREIGN KEY (`MB_Users_idUser`)
    REFERENCES `mobilityJobBD`.`MB_Users` (`idMB_User`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobilityJobBD`.`MB_Multimedia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mobilityJobBD`.`MB_Multimedia` (
  `idMB_Multimedia` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fileExtension` VARCHAR(45) NOT NULL,
  `videoExtension` VARCHAR(45) NOT NULL,
  `linkExtension` VARCHAR(45) NOT NULL,
  `MB_Services_idMB_Services` INT UNSIGNED NOT NULL,
  `MB_Users_idMB_User` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idMB_Multimedia`),
  UNIQUE INDEX `idMB_Multimedia_UNIQUE` (`idMB_Multimedia` ASC) VISIBLE,
  INDEX `fk_MB_Multimedia_MB_Services1_idx` (`MB_Services_idMB_Services` ASC) VISIBLE,
  INDEX `fk_MB_Multimedia_MB_Users1_idx` (`MB_Users_idMB_User` ASC) VISIBLE,
  CONSTRAINT `fk_MB_Multimedia_MB_Services1`
    FOREIGN KEY (`MB_Services_idMB_Services`)
    REFERENCES `mobilityJobBD`.`MB_Services` (`idMB_Services`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MB_Multimedia_MB_Users1`
    FOREIGN KEY (`MB_Users_idMB_User`)
    REFERENCES `mobilityJobBD`.`MB_Users` (`idMB_User`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobilityJobBD`.`MB_Service_Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mobilityJobBD`.`MB_Service_Status` (
  `idMB_Service_Status` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `statusService` VARCHAR(45) NOT NULL,
  `dateServiceIn` VARCHAR(45) NOT NULL,
  `dateServiceEnd` VARCHAR(45) NOT NULL,
  `comentService` VARCHAR(45) NOT NULL,
  `qualifyService` INT(45) NOT NULL,
  `MB_Services_idMB_Services` INT UNSIGNED NOT NULL,
  `MB_Users_idMB_User` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idMB_Service_Status`),
  UNIQUE INDEX `idMB_Service_Status_UNIQUE` (`idMB_Service_Status` ASC) VISIBLE,
  INDEX `fk_MB_Service_Status_MB_Services1_idx` (`MB_Services_idMB_Services` ASC) VISIBLE,
  INDEX `fk_MB_Service_Status_MB_Users1_idx` (`MB_Users_idMB_User` ASC) VISIBLE,
  CONSTRAINT `fk_MB_Service_Status_MB_Services1`
    FOREIGN KEY (`MB_Services_idMB_Services`)
    REFERENCES `mobilityJobBD`.`MB_Services` (`idMB_Services`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MB_Service_Status_MB_Users1`
    FOREIGN KEY (`MB_Users_idMB_User`)
    REFERENCES `mobilityJobBD`.`MB_Users` (`idMB_User`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobilityJobBD`.`MB_Errors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mobilityJobBD`.`MB_Errors` (
  `idMB_Errors` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descriptionError` VARCHAR(45) NOT NULL,
  `codeError` INT(3) NOT NULL,
  `creationDateError` DATE NOT NULL,
  `statusError` VARCHAR(45) NOT NULL,
  `plattformError` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMB_Errors`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mobilityJobBD`.`MB_CodeError`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mobilityJobBD`.`MB_CodeError` (
  `idMB_CodeError` INT NOT NULL,
  `codeMBError` INT NOT NULL,
  `descriptionMBError` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMB_CodeError`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
